### ISSUE TITLE
Great job, Oleg!

### ISSUE THREAD

**Issue by MongooseRC** [movoleg/aqua-controller#1]
Maybe in next version may include the total light intensity.

**Comment by movoleg** [comment]
I think it is done

**Comment by Arr2mil** [comment]
Hi my name is arran. I was pointed this way to ask about your evergrow wifi controller???you still produce them. 👍

**Comment by 3klips** [comment]
> Hi my name is arran. I was pointed this way to ask about your evergrow wifi controller???you still produce them. 👍

Hello, I was wondering the same, I'have some ESP32 at home, is it possible to connect ESP32 to the default factory board?

Thanks
